import platform
import subprocess
from pathlib import Path

# ── Project layout ────────────────────────────────────────────────────────────
PROJECT_DIR  = Path(__file__).resolve().parent.parent
DATA_DIR     = PROJECT_DIR / "data"
BACKUP_DIR   = PROJECT_DIR / "backups"

# ── Source DB (never schema-altered, committed to repo at data/ds_wiki.db) ────
SOURCE_DB    = DATA_DIR / "ds_wiki.db"

# ── Built artifacts (gitignored, generated by sync.py) ────────────────────────
HISTORY_DB   = DATA_DIR / "wiki_history.db"
CHROMA_DIR   = DATA_DIR / "chroma_db"

# ── Device & Embedding Auto-Detection ────────────────────────────────────────

def _detect_device() -> tuple[str, str]:
    """Auto-detect available device (cuda/mps/cpu) and select embedding model.

    Returns:
        (device_type, embed_model, embed_dim)
        - device_type: "cuda" (RTX 2000+ on Windows/Linux), "mps" (Apple Silicon),
                       "cpu" (fallback)
        - embed_model: "BAAI/bge-large-en-v1.5" (1024-dim) if GPU available,
                       "BAAI/bge-base-en-v1.5" (768-dim) otherwise
    """
    system = platform.system()

    # ── Check for CUDA (Windows/Linux with NVIDIA GPU) ────────────────────────
    if system in ("Windows", "Linux"):
        try:
            result = subprocess.run(
                ["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.returncode == 0:
                gpu_name = result.stdout.strip().split('\n')[0]
                print(f"[OK] CUDA GPU detected: {gpu_name}")
                return "cuda", "BAAI/bge-large-en-v1.5", 1024
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

    # ── Check for Metal Performance Shaders (Apple Silicon) ────────────────────
    if system == "Darwin":
        try:
            result = subprocess.run(
                ["system_profiler", "SPDisplaysDataType"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if "Apple" in result.stdout:
                print("[OK] Apple Silicon (MPS) detected")
                return "mps", "BAAI/bge-large-en-v1.5", 1024
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

    # ── Fallback to CPU ────────────────────────────────────────────────────────
    print("[WARN] No GPU detected, using CPU (slower embeddings)")
    return "cpu", "BAAI/bge-base-en-v1.5", 768


# Auto-detect on import
DEVICE, EMBED_MODEL, EMBED_DIM = _detect_device()

# ── Embedding ─────────────────────────────────────────────────────────────────
CHROMA_COLLECTION = "ds_wiki"

# ── Cross-encoder reranking (Phase 3B) ────────────────────────────────────────
CROSS_ENCODER_MODEL   = "cross-encoder/ms-marco-MiniLM-L-12-v2"
CROSS_ENCODER_ENABLED = True    # gate: set False to skip reranking (CPU fallback)
RERANK_TOP_K          = 20      # retrieve more candidates when reranking is on

# ── Search defaults ───────────────────────────────────────────────────────────
TOP_K_NEIGHBORS  = 5    # stored in history per chunk
DEFAULT_SEARCH_K = 5    # default n_results for search queries
DRIFT_THRESHOLD  = 0.05 # cosine distance — flag as "changed" if above this

# ── Link confidence tiers (derived from cosine similarity, not subjective) ────
# "1"   ≥ 0.90  — definitionally certain (structural, high-signal)
# "1.5" 0.85–0.89 — strong semantic bond, not definitional (half-tier)
# "2"   0.82–0.84 — plausible transitional connection, needs review
TIER_THRESHOLDS = [(0.90, "1"), (0.85, "1.5"), (0.82, "2")]

def score_to_tier(score: float) -> str:
    """Map a cosine similarity score to an objective confidence tier."""
    for threshold, tier in TIER_THRESHOLDS:
        if score >= threshold:
            return tier
    return "2"
